export type VastgoedkansStatus = 'te_beoordelen'|'onderzoek'|'brief_voorbereiden'|'opvolgen'|'wachten'|'positieve_reactie'|'afgevallen'|'gepromoveerd';
export type VastgoedkansHerkomst = 'handmatig'|'csv_import'|'bag_selectie'|'kaart_selectie'|'externe_bron';
export type EigenaarOnderzoekStatus = 'niet_gestart'|'bezig'|'bekend'|'niet_gevonden';
export type BriefStatus = 'niet_gestart'|'voorbereiden'|'klaar'|'verzonden'|'reactie_ontvangen';
export interface Vastgoedkans { id:string; kansnummer:string|null; adres:string|null; postcode:string|null; plaats:string|null; provincie:string|null; typeVastgoed:string|null; korteOmschrijving:string|null; herkomst:VastgoedkansHerkomst; herkomstReferentie:string|null; selectieprofielId:string|null; selectierunId:string|null; bagPandId:string|null; bagVerblijfsobjectId:string|null; algoritmeScore:number|null; scoreUitleg:string|null; status:VastgoedkansStatus; prioriteit:number; eigenaarStatus:EigenaarOnderzoekStatus; briefStatus:BriefStatus; volgendeActieDatum:string|null; volgendeActieOmschrijving:string|null; redenInteressant:string|null; notities:string|null; objectId:string|null; createdAt:string; updatedAt:string; }
export const STATUS_LABEL:Record<VastgoedkansStatus,string>={te_beoordelen:'Te beoordelen',onderzoek:'Onderzoek',brief_voorbereiden:'Brief voorbereiden',opvolgen:'Opvolgen',wachten:'Wachten',positieve_reactie:'Positieve reactie',afgevallen:'Afgevallen',gepromoveerd:'Gepromoveerd'};
export const STATUS_VOLGORDE:VastgoedkansStatus[]=['te_beoordelen','onderzoek','brief_voorbereiden','opvolgen','wachten','positieve_reactie','afgevallen','gepromoveerd'];
export const HERKOMST_LABEL:Record<VastgoedkansHerkomst,string>={handmatig:'Handmatig',csv_import:'CSV-import',bag_selectie:'BAG-selectie',kaart_selectie:'Kaartselectie',externe_bron:'Externe bron'};
export const EIGENAAR_LABEL:Record<EigenaarOnderzoekStatus,string>={niet_gestart:'Niet gestart',bezig:'Bezig',bekend:'Bekend',niet_gevonden:'Niet gevonden'};
export const BRIEF_LABEL:Record<BriefStatus,string>={niet_gestart:'Niet gestart',voorbereiden:'Voorbereiden',klaar:'Klaar',verzonden:'Verzonden',reactie_ontvangen:'Reactie ontvangen'};
export const PRIORITEIT_LABEL:Record<number,string>={1:'P1 — Direct oppakken',2:'P2 — Hoog',3:'P3 — Normaal',4:'P4 — Laag',5:'P5 — Parkeren'};
export const kansTitel=(k:Vastgoedkans)=>k.korteOmschrijving?.trim()||[k.adres,k.postcode,k.plaats].filter(Boolean).join(', ')||'(adres ontbreekt)';
