export type VastgoedkansStatus = 'te_beoordelen'|'onderzoek'|'brief_voorbereiden'|'opvolgen'|'wachten'|'positieve_reactie'|'afgevallen'|'gepromoveerd';
export type VastgoedkansHerkomst = 'handmatig'|'csv_import'|'bag_selectie'|'kaart_selectie'|'externe_bron';
export type EigenaarOnderzoekStatus = 'niet_gestart'|'bezig'|'bekend'|'niet_gevonden';
export type KadasterOnderzoekStatus = 'niet_gestart'|'handmatig_onderzoek'|'gegevens_bekend'|'niet_gevonden';
export type BriefStatus = 'niet_gestart'|'voorbereiden'|'klaar'|'verzonden'|'reactie_ontvangen';
export type ReactieStatus = 'geen_reactie'|'reactie_ontvangen'|'interesse'|'geen_interesse'|'later_contact'|'onbereikbaar';
export interface Vastgoedkans { id:string; kansnummer:string|null; adres:string|null; postcode:string|null; plaats:string|null; provincie:string|null; typeVastgoed:string|null; korteOmschrijving:string|null; herkomst:VastgoedkansHerkomst; herkomstReferentie:string|null; selectieprofielId:string|null; selectierunId:string|null; bagPandId:string|null; bagVerblijfsobjectId:string|null; algoritmeScore:number|null; scoreUitleg:string|null; status:VastgoedkansStatus; prioriteit:number; eigenaarStatus:EigenaarOnderzoekStatus; eigenaarNaam:string|null; eigenaarBron:string|null; eigenaarRelatieId:string|null; eigenaarLaatstGecontroleerdOp:string|null; kadasterStatus:KadasterOnderzoekStatus; kadastraleAanduiding:string|null; kadasterLaatstGecontroleerdOp:string|null; onderzoeksnotities:string|null; briefStatus:BriefStatus; briefGeadresseerde:string|null; briefVerzendwijze:string|null; briefVerzondenOp:string|null; briefKenmerk:string|null; opvolgdatum:string|null; opvolgactie:string|null; reactieStatus:ReactieStatus; reactieOntvangenOp:string|null; reactieKanaal:string|null; reactieSamenvatting:string|null; reactieUitkomst:string|null; volgendeActieDatum:string|null; volgendeActieOmschrijving:string|null; redenInteressant:string|null; notities:string|null; objectId:string|null; archivedAt:string|null; archivedBy:string|null; archivedReason:string|null; createdAt:string; updatedAt:string; }
export const STATUS_LABEL:Record<VastgoedkansStatus,string>={te_beoordelen:'Te beoordelen',onderzoek:'Onderzoek',brief_voorbereiden:'Brief voorbereiden',opvolgen:'Opvolgen',wachten:'Wachten',positieve_reactie:'Positieve reactie',afgevallen:'Afgevallen',gepromoveerd:'Gepromoveerd'};
export const STATUS_VOLGORDE:VastgoedkansStatus[]=['te_beoordelen','onderzoek','brief_voorbereiden','opvolgen','wachten','positieve_reactie','afgevallen','gepromoveerd'];
export const HERKOMST_LABEL:Record<VastgoedkansHerkomst,string>={handmatig:'Handmatig',csv_import:'CSV-import',bag_selectie:'BAG-selectie',kaart_selectie:'Kaartselectie',externe_bron:'Externe bron'};
export const EIGENAAR_LABEL:Record<EigenaarOnderzoekStatus,string>={niet_gestart:'Niet gestart',bezig:'Bezig',bekend:'Bekend',niet_gevonden:'Niet gevonden'};
export const KADASTER_LABEL:Record<KadasterOnderzoekStatus,string>={niet_gestart:'Niet gestart',handmatig_onderzoek:'Handmatig onderzoek',gegevens_bekend:'Gegevens bekend',niet_gevonden:'Niet gevonden'};
export const BRIEF_LABEL:Record<BriefStatus,string>={niet_gestart:'Niet gestart',voorbereiden:'Voorbereiden',klaar:'Klaar',verzonden:'Verzonden',reactie_ontvangen:'Reactie ontvangen'};
export const REACTIE_LABEL:Record<ReactieStatus,string>={geen_reactie:'Geen reactie',reactie_ontvangen:'Reactie ontvangen',interesse:'Interesse',geen_interesse:'Geen interesse',later_contact:'Later contact',onbereikbaar:'Onbereikbaar'};
export const PRIORITEIT_LABEL:Record<number,string>={1:'P1 — Direct oppakken',2:'P2 — Hoog',3:'P3 — Normaal',4:'P4 — Laag',5:'P5 — Parkeren'};
export const kansTitel=(k:Vastgoedkans)=>k.korteOmschrijving?.trim()||[k.adres,k.postcode,k.plaats].filter(Boolean).join(', ')||'(adres ontbreekt)';
