import React,{createContext,useCallback,useContext,useEffect,useState} from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import type { Vastgoedkans,VastgoedkansStatus,VastgoedkansHerkomst,EigenaarOnderzoekStatus,KadasterOnderzoekStatus,BriefStatus } from '@/lib/vastgoedkansen';
const sb=supabase as any;
const fromDb=(r:any):Vastgoedkans=>({id:r.id,kansnummer:r.kansnummer,adres:r.adres,postcode:r.postcode,plaats:r.plaats,provincie:r.provincie,typeVastgoed:r.type_vastgoed,korteOmschrijving:r.korte_omschrijving,herkomst:r.herkomst,herkomstReferentie:r.herkomst_referentie,selectieprofielId:r.selectieprofiel_id,selectierunId:r.selectierun_id,bagPandId:r.bag_pand_id,bagVerblijfsobjectId:r.bag_verblijfsobject_id,algoritmeScore:r.algoritme_score,scoreUitleg:r.score_uitleg,status:r.status,prioriteit:r.prioriteit??3,eigenaarStatus:r.eigenaar_status,eigenaarNaam:r.eigenaar_naam,eigenaarBron:r.eigenaar_bron,eigenaarLaatstGecontroleerdOp:r.eigenaar_laatst_gecontroleerd_op,kadasterStatus:r.kadaster_status??'niet_gestart',kadastraleAanduiding:r.kadastrale_aanduiding,kadasterLaatstGecontroleerdOp:r.kadaster_laatst_gecontroleerd_op,onderzoeksnotities:r.onderzoeksnotities,briefStatus:r.brief_status,volgendeActieDatum:r.volgende_actie_datum,volgendeActieOmschrijving:r.volgende_actie_omschrijving,redenInteressant:r.reden_interessant,notities:r.notities,objectId:r.object_id,createdAt:r.created_at,updatedAt:r.updated_at});
export interface KansInput{adres?:string;postcode?:string;plaats?:string;provincie?:string;typeVastgoed?:string;korteOmschrijving?:string;herkomst?:VastgoedkansHerkomst;herkomstReferentie?:string;status?:VastgoedkansStatus;prioriteit?:number;eigenaarStatus?:EigenaarOnderzoekStatus;eigenaarNaam?:string;eigenaarBron?:string;eigenaarLaatstGecontroleerdOp?:string|null;kadasterStatus?:KadasterOnderzoekStatus;kadastraleAanduiding?:string;kadasterLaatstGecontroleerdOp?:string|null;onderzoeksnotities?:string;briefStatus?:BriefStatus;volgendeActieDatum?:string|null;volgendeActieOmschrijving?:string;redenInteressant?:string;notities?:string;bagPandId?:string;bagVerblijfsobjectId?:string;}
const snake=(x:KansInput)=>({adres:x.adres||null,postcode:x.postcode||null,plaats:x.plaats||null,provincie:x.provincie||null,type_vastgoed:x.typeVastgoed||null,korte_omschrijving:x.korteOmschrijving||null,herkomst:x.herkomst??'handmatig',herkomst_referentie:x.herkomstReferentie||null,status:x.status??'te_beoordelen',prioriteit:x.prioriteit??3,eigenaar_status:x.eigenaarStatus??'niet_gestart',eigenaar_naam:x.eigenaarNaam||null,eigenaar_bron:x.eigenaarBron||null,eigenaar_laatst_gecontroleerd_op:x.eigenaarLaatstGecontroleerdOp||null,kadaster_status:x.kadasterStatus??'niet_gestart',kadastrale_aanduiding:x.kadastraleAanduiding||null,kadaster_laatst_gecontroleerd_op:x.kadasterLaatstGecontroleerdOp||null,onderzoeksnotities:x.onderzoeksnotities||null,brief_status:x.briefStatus??'niet_gestart',volgende_actie_datum:x.volgendeActieDatum||null,volgende_actie_omschrijving:x.volgendeActieOmschrijving||null,reden_interessant:x.redenInteressant||null,notities:x.notities||null,bag_pand_id:x.bagPandId||null,bag_verblijfsobject_id:x.bagVerblijfsobjectId||null});
type C={kansen:Vastgoedkans[];laden:boolean;refresh:()=>Promise<void>;addKans:(x:KansInput)=>Promise<void>;updateKans:(id:string,x:KansInput)=>Promise<void>;getKansById:(id:string)=>Vastgoedkans|undefined};
const Ctx=createContext<C|undefined>(undefined);
export function VastgoedkansenProvider({children}:{children:React.ReactNode}){const{user}=useAuth();const[kansen,setKansen]=useState<Vastgoedkans[]>([]);const[laden,setLaden]=useState(false);const refresh=useCallback(async()=>{if(!user){setKansen([]);return}setLaden(true);try{const{data,error}=await sb.from('vastgoedkansen').select('*').order('updated_at',{ascending:false});if(error)throw error;setKansen((data??[]).map(fromDb))}finally{setLaden(false)}},[user]);useEffect(()=>{refresh()},[refresh]);const addKans=useCallback(async(x:KansInput)=>{const{data,error}=await sb.from('vastgoedkansen').insert({...snake(x),aangemaakt_door:user?.id??null}).select().single();if(error)throw error;setKansen(p=>[fromDb(data),...p])},[user]);const updateKans=useCallback(async(id:string,x:KansInput)=>{const{data,error}=await sb.from('vastgoedkansen').update(snake(x)).eq('id',id).select().single();if(error)throw error;setKansen(p=>p.map(k=>k.id===id?fromDb(data):k))},[]);const getKansById=useCallback((id:string)=>kansen.find(k=>k.id===id),[kansen]);return <Ctx.Provider value={{kansen,laden,refresh,addKans,updateKans,getKansById}}>{children}</Ctx.Provider>};
export const useVastgoedkansen=()=>{const c=useContext(Ctx);if(!c)throw new Error('useVastgoedkansen buiten provider');return c};
