import { useEffect, useMemo, useState } from 'react';
import { Coins, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { supabase } from '@/integrations/supabase/client';
import type { Vastgoedkans } from '@/lib/vastgoedkansen';
import { parseObjectAdres } from '@/lib/kadaster/adres';
import { useKadasterObjectinformatie } from '@/hooks/useKadasterObjectinformatie';
import { useKadasterProductCatalogus } from '@/hooks/useKadasterProductCatalogus';
import { formatKadasterPrijs, kadasterProductPrijs } from '@/lib/kadaster/tarieven';
import type { KadasterAdresInput, KadasterRequestInput } from '@/lib/kadaster/types';

interface Props { open:boolean; onOpenChange:(open:boolean)=>void; kansen:Vastgoedkans[]; onKlaar?:()=>void; }
type Status='aanvragen'|'aanwezig'|'geblokkeerd';
interface Rij { kans:Vastgoedkans; status:Status; adres:KadasterAdresInput|null; label:string; reden:string; }
function compactPc(v:string|null|undefined):string{return(v??'').replace(/\s+/g,'').toUpperCase()}
function preflightAdres(k:Vastgoedkans):{adres:KadasterAdresInput|null;reden:string}{const p=parseObjectAdres(k.adres??'',k.postcode,k.plaats);const pc=compactPc(p.postcode);if(!/^\d{4}[A-Z]{2}$/.test(pc))return{adres:null,reden:'Geen geldige postcode.'};if(p.huisnummers.length!==1)return{adres:null,reden:p.huisnummers.length>1?'Meerdere mogelijke huisnummers; controleer dit pand individueel.':'Geen betrouwbaar huisnummer.'};const h=p.huisnummers[0];return{adres:{postalcode:pc,houseNumber:h.huisnummer,houseLetter:h.huisletter??null,houseNumberAddition:h.toevoeging??null},reden:'Adres is eenduidig voor Kadaster.'}}
function label(k:Vastgoedkans):string{return[k.adres,k.postcode,k.plaats].filter(Boolean).join(', ')||k.kansnummer||k.id}

export default function PandenverkennerBulkKadasterDialog({open,onOpenChange,kansen,onKlaar}:Props){
  const[rijen,setRijen]=useState<Rij[]>([]);const[geselecteerd,setGeselecteerd]=useState<Set<string>>(new Set());const[laden,setLaden]=useState(false);const[bevestig,setBevestig]=useState(false);const[uitvoeren,setUitvoeren]=useState(false);const mutation=useKadasterObjectinformatie();const catalogus=useKadasterProductCatalogus(open);const ids=useMemo(()=>kansen.map(k=>k.id),[kansen]);const idsKey=ids.join('|');
  const rechtenItem=useMemo(()=>catalogus.data?.products.find(p=>p.code==='rechten')??null,[catalogus.data]);const rechtenPrijs=kadasterProductPrijs('rechten',rechtenItem?.priceEur);

  useEffect(()=>{if(!open||ids.length===0){setRijen([]);setGeselecteerd(new Set());return}let stop=false;const laad=async()=>{setLaden(true);try{const{data,error}=await(supabase as any).from('kadaster_data_records').select('vastgoedkans_id,product_code,status,fetched_at').in('vastgoedkans_id',ids).eq('product_code','rechten');if(error)throw new Error(error.message);const aanwezig=new Set((data??[]).filter((r:any)=>r.status==='geleverd'||r.status==='gedeeltelijk').map((r:any)=>r.vastgoedkans_id));const volgende=kansen.map((k):Rij=>{if(aanwezig.has(k.id))return{kans:k,status:'aanwezig',adres:null,label:label(k),reden:'Rechten zijn al aanwezig; geen nieuwe betaalde aanvraag.'};const pf=preflightAdres(k);return pf.adres?{kans:k,status:'aanvragen',adres:pf.adres,label:label(k),reden:pf.reden}:{kans:k,status:'geblokkeerd',adres:null,label:label(k),reden:pf.reden}});if(!stop){setRijen(volgende);setGeselecteerd(new Set(volgende.filter(r=>r.status==='aanvragen').map(r=>r.kans.id)))}}catch(e){if(!stop)toast.error(e instanceof Error?e.message:'Kadasterpreflight laden mislukt.')}finally{if(!stop)setLaden(false)}};void laad();return()=>{stop=true}},[open,idsKey]);
  const aanvraagRijen=rijen.filter(r=>r.status==='aanvragen'&&geselecteerd.has(r.kans.id));const totaal=aanvraagRijen.length*rechtenPrijs;
  const toggle=(id:string)=>setGeselecteerd(v=>{const n=new Set(v);n.has(id)?n.delete(id):n.add(id);return n});
  const voerUit=async()=>{if(uitvoeren||aanvraagRijen.length===0)return;setBevestig(false);setUitvoeren(true);let gelukt=0;try{for(const r of aanvraagRijen){const input:KadasterRequestInput={modus:'kadaster',adres:r.adres!,producten:['rechten'],context:{vastgoedkans_id:r.kans.id},persist:true,includePdf:true};const resp=await mutation.mutateAsync(input);if(!resp.persist?.ok)throw new Error(`Kadastergegevens voor ${r.label} zijn opgehaald maar niet veilig opgeslagen. Stop de bulkactie en controleer dit dossier.`);gelukt++}toast.success(`${gelukt} Kadaster-rechtenaanvraag${gelukt===1?'':'en'} opgeslagen.`);onKlaar?.();onOpenChange(false)}catch(e){toast.error(e instanceof Error?`${e.message} (${gelukt} eerdere aanvraag${gelukt===1?'':'en'} in deze ronde wel voltooid.)`:'Bulk Kadaster mislukt.')}finally{setUitvoeren(false)}};
  const telling=useMemo(()=>({aanvragen:rijen.filter(r=>r.status==='aanvragen').length,aanwezig:rijen.filter(r=>r.status==='aanwezig').length,blok:rijen.filter(r=>r.status==='geblokkeerd').length}),[rijen]);
  return <><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-3xl max-h-[88vh] overflow-y-auto"><DialogHeader><DialogTitle>Bulk Kadaster — Pandenverkenner</DialogTitle><DialogDescription>Alleen geselecteerde regels worden na een aparte kostenbevestiging aangevraagd. Er wordt nooit automatisch betaald op basis van alleen de selectie.</DialogDescription></DialogHeader>{laden?<div className="flex items-center gap-2 py-8 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin"/>Preflight uitvoeren…</div>:<><div className="flex flex-wrap gap-2"><Badge variant="outline">{telling.aanvragen} aanvraagbaar</Badge><Badge variant="secondary">{telling.aanwezig} al aanwezig</Badge>{telling.blok>0&&<Badge variant="destructive">{telling.blok} geblokkeerd</Badge>}</div><div className="divide-y rounded-md border">{rijen.map(r=><label key={r.kans.id} className="flex items-start gap-3 p-3 text-sm"><Checkbox className="mt-0.5" checked={geselecteerd.has(r.kans.id)} disabled={r.status!=='aanvragen'||uitvoeren} onCheckedChange={()=>toggle(r.kans.id)}/><div className="min-w-0 flex-1"><p className="font-medium">{r.label}</p><p className="mt-1 text-xs text-muted-foreground">{r.reden}</p></div><Badge variant={r.status==='geblokkeerd'?'destructive':r.status==='aanwezig'?'secondary':'outline'}>{r.status==='aanvragen'?'Aanvragen':r.status==='aanwezig'?'Aanwezig':'Geblokkeerd'}</Badge></label>)}</div><div className="rounded-md border bg-muted/20 p-3 text-sm"><div className="flex justify-between"><span>Geselecteerd</span><strong>{aanvraagRijen.length}</strong></div><div className="mt-1 flex justify-between"><span>Rechten per pand</span><strong>{formatKadasterPrijs(rechtenPrijs)}</strong></div><div className="mt-1 flex justify-between border-t pt-2"><span>Geschatte totale Kadasterkosten</span><strong>{formatKadasterPrijs(totaal)}</strong></div></div></>}<DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Annuleren</Button><Button onClick={()=>setBevestig(true)} disabled={laden||uitvoeren||aanvraagRijen.length===0||!rechtenItem}><Coins className="mr-1.5 h-4 w-4"/>{uitvoeren?'Bezig…':`${aanvraagRijen.length} aanvragen`}</Button></DialogFooter></DialogContent></Dialog><AlertDialog open={bevestig} onOpenChange={setBevestig}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Kadasterkosten bevestigen</AlertDialogTitle><AlertDialogDescription>Je staat op het punt {aanvraagRijen.length} betaalde Rechten-aanvraag{aanvraagRijen.length===1?'':'en'} uit te voeren. Geschatte totale kosten: {formatKadasterPrijs(totaal)}. Elke aanvraag wordt afzonderlijk aan de betreffende Vastgoedkans opgeslagen, inclusief Kadasterbericht.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Annuleren</AlertDialogCancel><AlertDialogAction onClick={()=>void voerUit()}>Kosten bevestigen & aanvragen</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
