REVOKE EXECUTE ON FUNCTION public.prevent_crm_objectnummer_update() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.vastgoedrekenen_bronimport_mapping_actor_guard() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.vastgoedrekenen_enforce_bronpakket_actor() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.vastgoedrekenen_lock_approved_package_entries() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.vastgoedrekenen_lock_bronpakket_metadata() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.vastgoedrekenen_snapshot_bronpakket() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.vastgoedrekenen_validate_bronpakket_approval() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.vastgoedkans_nummer_toekennen() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.vastgoedrekenen_bronpakket_touch_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_updated_at_column() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activate_off_market_cron(text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.next_crm_objectnummer() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.generate_refnummer() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.off_market_bron_stats() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.off_market_promote_to_object(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.vastgoedrekenen_import_codes_valid(text, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.vastgoedrekenen_import_kengetallen(uuid, jsonb, jsonb, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_intern_gebruiker(uuid) FROM PUBLIC, anon;