
ALTER TABLE public.sell_off_units
  ADD COLUMN IF NOT EXISTS component_id uuid,
  ADD COLUMN IF NOT EXISTS unit_label text,
  ADD COLUMN IF NOT EXISTS unit_type text,
  ADD COLUMN IF NOT EXISTS surface_gbo numeric,
  ADD COLUMN IF NOT EXISTS surface_vvo numeric,
  ADD COLUMN IF NOT EXISTS surface_bvo numeric,
  ADD COLUMN IF NOT EXISTS strategy text,
  ADD COLUMN IF NOT EXISTS sale_price_total bigint,
  ADD COLUMN IF NOT EXISTS sale_price_per_m2 numeric,
  ADD COLUMN IF NOT EXISTS sale_price_source text,
  ADD COLUMN IF NOT EXISTS sale_costs_pct numeric,
  ADD COLUMN IF NOT EXISTS sale_costs_amount bigint,
  ADD COLUMN IF NOT EXISTS legal_costs bigint,
  ADD COLUMN IF NOT EXISTS renovation_costs bigint,
  ADD COLUMN IF NOT EXISTS splitting_costs bigint,
  ADD COLUMN IF NOT EXISTS transformation_costs bigint,
  ADD COLUMN IF NOT EXISTS net_sale_proceeds bigint,
  ADD COLUMN IF NOT EXISTS hold_monthly_rent bigint,
  ADD COLUMN IF NOT EXISTS hold_annual_rent bigint,
  ADD COLUMN IF NOT EXISTS hold_rent_source text,
  ADD COLUMN IF NOT EXISTS hold_valuation_method text,
  ADD COLUMN IF NOT EXISTS hold_bar numeric,
  ADD COLUMN IF NOT EXISTS hold_nar numeric,
  ADD COLUMN IF NOT EXISTS hold_factor numeric,
  ADD COLUMN IF NOT EXISTS hold_value_manual bigint,
  ADD COLUMN IF NOT EXISTS hold_value_calculated bigint,
  ADD COLUMN IF NOT EXISTS contribution_to_scenario_value bigint,
  ADD COLUMN IF NOT EXISTS notes text,
  ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;
