// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list_relaties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_relaties_default = defineTool({
  name: "list_relaties",
  title: "Lijst relaties",
  description: "Lijst met CRM-relaties (kopers, verkopers, huurders, contacten) van de ingelogde gebruiker. Ondersteunt zoeken op naam/plaats en filtert soft-deleted records uit.",
  inputSchema: {
    zoekterm: z.string().trim().max(120).optional().describe("Zoekterm op bedrijfsnaam, contactnaam of plaats."),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ zoekterm, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("relaties").select("id, bedrijfsnaam, contactnaam, plaats, telefoon, email, relatietype, categorie, created_at").is("soft_deleted_at", null).order("updated_at", { ascending: false }).limit(limit);
    if (zoekterm) {
      const like = `%${zoekterm}%`;
      q = q.or(
        `bedrijfsnaam.ilike.${like},contactnaam.ilike.${like},plaats.ilike.${like}`
      );
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} relaties gevonden.` }],
      structuredContent: { relaties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_objecten.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_objecten_default = defineTool2({
  name: "list_objecten",
  title: "Lijst objecten",
  description: "Lijst met vastgoedobjecten (aanbod) van de ingelogde gebruiker. Geeft kernvelden voor overzicht en beslissing: locatie, type, vraagprijs, huur, oppervlakte, status.",
  inputSchema: {
    zoekterm: z2.string().trim().max(120).optional().describe("Zoekterm op naam, adres of plaats."),
    status: z2.enum(["te_beoordelen", "actief", "onder_bod", "verkocht", "verhuurd", "ingetrokken"]).optional(),
    plaats: z2.string().trim().max(80).optional(),
    limit: z2.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ zoekterm, status, plaats, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("objecten").select(
      "id, intern_referentienummer, objectnaam, adres, plaats, provincie, type_vastgoed, subcategorie, vraagprijs, huurinkomsten, oppervlakte_vvo, oppervlakte, bouwjaar, status, verhuurstatus, bruto_aanvangsrendement, energielabel, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (plaats) q = q.ilike("plaats", `%${plaats}%`);
    if (zoekterm) {
      const like = `%${zoekterm}%`;
      q = q.or(
        `objectnaam.ilike.${like},adres.ilike.${like},plaats.ilike.${like},intern_referentienummer.ilike.${like}`
      );
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} objecten gevonden.` }],
      structuredContent: { objecten: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_deals.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_deals_default = defineTool3({
  name: "list_deals",
  title: "Lijst deals",
  description: "Lijst met deals (pipeline) voor de ingelogde gebruiker met fase, interessegraad, indicatief bod, en gekoppelde relatie/object. Sluit gearchiveerde deals standaard uit.",
  inputSchema: {
    fase: z3.string().trim().max(40).optional().describe("Filter op deal-fase."),
    inclusief_archief: z3.boolean().default(false),
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ fase, inclusief_archief, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("deals").select(
      "id, fase, interessegraad, indicatief_bod, datum_eerste_contact, datum_follow_up, verwachte_closingdatum, commissie_pct, commissie_bedrag, dd_status, is_archived, closed_at, object_id, relatie_id, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit);
    if (!inclusief_archief) q = q.eq("is_archived", false);
    if (fase) q = q.eq("fase", fase);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} deals gevonden.` }],
      structuredContent: { deals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_taken.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_taken_default = defineTool4({
  name: "list_taken",
  title: "Lijst taken",
  description: "Lijst met openstaande taken van de ingelogde gebruiker met titel, deadline, prioriteit en status. Sluit standaard afgeronde en geannuleerde taken uit.",
  inputSchema: {
    inclusief_afgerond: z4.boolean().default(false),
    limit: z4.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ inclusief_afgerond, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet geauthenticeerd" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("taken").select("id, titel, omschrijving, deadline, prioriteit, status, type, relatie_id, object_id, deal_id, created_at, updated_at").order("deadline", { ascending: true, nullsFirst: false }).limit(limit);
    if (!inclusief_afgerond) q = q.not("status", "in", "(afgerond,geannuleerd)");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} taken gevonden.` }],
      structuredContent: { taken: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ljudxyrqoifhfikueric";
var mcp_default = defineMcp({
  name: "bito-vastgoed-mcp",
  title: "Bito Vastgoed CRM",
  version: "0.1.0",
  instructions: "Read-only toegang tot het Bito Vastgoed CRM: relaties, objecten (aanbod), deals en taken. Alle tools draaien onder de ingelogde gebruiker; RLS bepaalt zichtbaarheid. Gebruik `list_relaties`, `list_objecten`, `list_deals` en `list_taken` om commercieel overzicht te krijgen.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_relaties_default, list_objecten_default, list_deals_default, list_taken_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
